# -*- coding: utf-8 -*-
"""youtubeData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/thecsbabe/plotly-youtube-data/blob/main/youtubeData.ipynb
"""

#importing data
from google.colab import files
uploaded = files.upload()

#packages
import pandas as pd
import io

youtubeData = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels.csv']))
display(youtubeData)

youtubeData = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels.csv']))
display(youtubeData)

#remove the commas from the integers
youtubeData = youtubeData.replace(',', '', regex=True)
display(youtubeData)

#Histogram
import plotly.express as px

fig = px.histogram(youtubeData, x='subscribers', title = 'Subscriber Count')
fig.show()

#pie chart
fig = px.pie(youtubeData, values= 'subscribers', names= 'category', title= 'Youtube Categories')
fig.show()

#Box plot

fig= px.box(youtubeData, y='started', title= 'Years Started')
fig.show()